MOCK_SOCIO_DATABASE = {
     "haldwani": {
        "location_id": 1,
        "ward_id": "WARD-HLD-01",
        "ward_name": "Haldwani Urban Core (Plains)",
        "latitude": 29.22,
        "longitude": 79.52,
        "terrain_type": "plain",
        "imd_base_threshold": 40.0,
        "elderly_ratio": 0.08,
        "density_per_km2": 1800,
        "grid_local_capacity": "stable",
    },
    "nainital": {
        "location_id": 2,
        "ward_id": "WARD-NKT-02",
        "ward_name": "Nainital Ridge Node (Hills)",
        "latitude": 29.38,
        "longitude": 79.45,
        "terrain_type": "hilly",
        "imd_base_threshold": 30.0, 
        "elderly_ratio": 0.12,
        "density_per_km2": 850,
        "grid_local_capacity": "critical",
    },
    "delhi": {
        "location_id": 3,
        "ward_id": "WARD-DLH-03",
        "ward_name": "Delhi Central Sector",
        "latitude": 28.61,
        "longitude": 77.20,
        "terrain_type": "plain",
        "imd_base_threshold": 40.0,
        "elderly_ratio": 0.09,
        "density_per_km2": 11000,
        "grid_local_capacity": "critical",
    },
    "mumbai": {
        "location_id": 4,
        "ward_id": "WARD-BOM-04",
        "ward_name": "Mumbai Coastal Node",
        "latitude": 19.07,
        "longitude": 72.87,
        "terrain_type": "coastal",
        "imd_base_threshold": 35.0,
        "elderly_ratio": 0.07,
        "density_per_km2": 21000,
        "grid_local_capacity": "stable",
    },
    "patna": {
        "location_id": 5,
        "ward_id": "WARD-PAT-05",
        "ward_name": "Patna Main (Bihar Region)",
        "latitude": 25.59,
        "longitude": 85.13,
        "terrain_type": "plain",
        "imd_base_threshold": 40.0,
        "elderly_ratio": 0.08,
        "density_per_km2": 3100,
        "grid_local_capacity": "stable",
    }
}
